#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    #colorscheme = "gruvbox"
    colorscheme = "dracula"
    background = "dark"
    guifont = "Ubuntu Mono 12"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_display_mode = false
    filemanager = "nerdtree"

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = "lsp"
filetypes = [
  "haskell",
  "python"
]

[[layers]]
name = "lang#haskell"

[[layers]]
name = "fzf"

[[layers]]
name = "git"


[[layers]]
name = "colorscheme"

[[custom_plugins]]
name = 'dracula/vim'
[[custom_plugins]]
name = 'neovimhaskell/haskell-vim'
[[custom_plugins]]
name = 'w0rp/ale'
[[custom_plugins]]
name = 'alx741/vim-hindent'
[[custom_plugins]]
name = 'neomake/neomake'
[[custom_plugins]]
name = 'kassio/neoterm'

