#!/bin/sh
xrandr --output eDP1 --primary --mode 1920x1080 --pos 3840x0 --rotate normal --output DP1 --mode 3840x2160 --pos 0x0 --scale 1x1 --rotate normal --output HDMI3 --off --output HDMI2 --off --output HDMI1 --off --output DP2 --off
